### ISSUE TITLE
Allow tinder like left and right swiping.

### ISSUE THREAD

**Issue by itsyogesh** [CrowdLinker/react-native-pager#11]
Hi Crowdlinker Team,

Thank you for the library, I've just tried it out and it felt really responsive. I was looking at a specific use case where the pager can register right-swiping to allow for the current card to be swiped right, rather than bringing the previous screen back. I was going through the props but I couldn't find anything that I could use.

Let me know if you need any other details regarding the usecase.

**Comment by ajsmth** [comment]
hi there - thanks so much. i too have thought of this use case but haven't come up with a solution just yet. my initial thoughts would be that you would have to pop the top child after swiping it away so that it couldn't come back. i will think about this a little bit, if you come up with a solution it would be awesome if you could share! thanks

**Comment by ajsmth** [comment]
following up on this -- i've tried a couple different approaches with no luck. i dont think this library is the right tool for the job, but i have a good idea of how this kind of thing could be done. let me know if you want some guidance on building something to achieve this kind of component. cheers

**Comment by itsyogesh** [comment]
So I've been looking at some apps who do the pagination along these lines, and essentially the idea is not to pop the top screen off but rather allowing for going to the previous screen with a tap. Here is a video that explains this.
![19-10-10-22-04-37 2019-10-10 22_23_25](https://user-images.githubusercontent.com/1210943/66589757-d9a6cb80-ebac-11e9-9cdb-70eb7acfb98e.gif)

But I understand how this could be difficult, and I would love to understand how should I go about building this. Especially when the next clamp is 0, kinda like the stacked cards example. I am also a fan of the transformation config for cards, its genius :)
