### ISSUE TITLE
Performance with large amount of data

### ISSUE THREAD

**Issue by Hirbod** [CrowdLinker/react-native-pager#14]
Hi, your component looks great and very promising. I was about to build something using FlatList horizontal and pagingEnabled, because I need to handle up to thousands of slides. Will this be still performant with your library? I haven’t digged in very deeply so far into your codebase, but it looks like you already kinda lazy render the elements, right?

Thank you!

**Comment by ajsmth** [comment]
hi there -- i think so, but know that it unmounts components outside of the `adjacentChildren` range, so long as your slides don't need to store their latent state (e.g scrollposition or some kind of other UI state) then it might be a good option

**Comment by Hirbod** [comment]
For now, it will be just a big image and some profile informations (building a facebook/instagram story viewer), so this might be a good one for me. I'm excited to try out

Do you think 3D Cube transitions would be possible? I actually want to replace this with native-pager now. If this is not feasible I'll go for another animation. But would be nice to have.

https://github.com/wcandillon/can-it-be-done-in-react-native/blob/master/season1/instagram-stories/components/Stories3.js

This approach uses reanimated.
(See my GIF attached, looks great, but it lacks badly in performance after only 20 slides, since it uses a ScrollView and renders everything at once). Do you think something like this is possible? Code is already nearly there. 

![ezgif com-optimize](https://user-images.githubusercontent.com/504909/70098283-cef83800-162b-11ea-8396-b7e8ee023d8f.gif)

**Comment by ajsmth** [comment]
i would think so - if you're familiar with and are using interpolated values, then you should be able to update transform properties of your screens -- i would look at the `pageInterpolation` prop

**Comment by Hirbod** [comment]
I'm pretty new to it, I'll try to achieve it. Might be worth for your examples though if this is achievable. (Would drop a 100$ donation/bounty for it)

**Comment by Hirbod** [comment]
Your Component IS JUST AWESOME. I had one special component which relied on FileSystem (for caching image into filesystem) which made your component stutter extremely (UI drops to 20-30fps), but after removing it, it runs just SO AMAZINGLY smooth. 59-60 fps no matter how fast I slide. This is by far the best swiping component I've seen.

My offer is valid. 100 $ tip for integrating the cube transition (nice to have with the mask, if not possible its even ok without)
