### ISSUE TITLE
Gesture Handler issues

### ISSUE THREAD

**Issue by Hirbod** [CrowdLinker/react-native-pager#16]
I open the Pager in Fullscreen using react-native-modalize and a Portal (to hide Navigation tabs). Modalize has a feature "flick / swipe to dismiss", so when I swipe down vertically, I can pull the modal down to close it. (following the finger till threshold)

Pager seems not to bubbling up the gestures, therefore, my vertical pull never reaches the wrapping modal. Is there any chance I could stop preventing the gesture? (horizontal is fine for me, I need to bubble up the vertical one)

**Comment by ajsmth** [comment]
i'm not sure, but i think you can get something working using the `panProps` which takes any PanGestureHandler config available from `react-native-gesture-handler` likely the activeOffsetY prop in your case

**Comment by Hirbod** [comment]
Do you have a little example for me?

**Comment by ajsmth** [comment]
no, but here's a reference in their docs: https://kmagiera.github.io/react-native-gesture-handler/docs/handler-pan.html#activeoffsety

**Comment by Hirbod** [comment]
I love u, thank you very much! It actually took me a hour to figure out how this works, because it wasn't working like I wish before I also added a failOffset and the activeOffsetX.

```
            panProps={{
                activeOffsetY: [-0, 10],
                failOffsetY: [-50, 5],
                activeOffsetX: [-1,1]
            }}
```

Now it really feels absolut great and native.

![ezgif com-optimize (2)](https://user-images.githubusercontent.com/504909/70117225-2e266e80-1665-11ea-8119-9fa23d24a2a8.gif)

**Comment by ajsmth** [comment]
awesome - glad it worked out!

**Comment by Hirbod** [comment]
Might be worth a notice in the readme maybe ?
