### ISSUE TITLE
Crashing on android

### ISSUE THREAD

**Issue by Hirbod** [CrowdLinker/react-native-pager#17]
Version 10 (haven't tested on any other version)
<img width="401" alt="Bildschirmfoto 2019-12-04 um 02 28 45" src="https://user-images.githubusercontent.com/504909/70104834-995d4a00-163f-11ea-968b-bb70d5580ff0.png">

```log
Error while updating property 'accessibilityRole' of a view managed by: RCTView

null

Invalid accessibility role value: tablist
updateViewProp
    ViewManagersPropertyCache.java:95
setProperty
    ViewManagerPropertyUpdater.java:132
updateProps
    ViewManagerPropertyUpdater.java:51
updateProperties
    ViewManager.java:37
createView
    NativeViewHierarchyManager.java:245
execute
    UIViewOperationQueue.java:200
dispatchPendingNonBatchedOperations
    UIViewOperationQueue.java:1109
doFrameGuarded
    UIViewOperationQueue.java:1080
doFrame
    GuardedFrameCallback.java:29
doFrame
    ReactChoreographer.java:166
doFrame
    ChoreographerCompat.java:84
run
    Choreographer.java:964
doCallbacks
    Choreographer.java:790
doFrame
    Choreographer.java:721
run
    Choreographer.java:951
handleCallback
    Handler.java:883
dispatchMessage
    Handler.java:100
loop
    Looper.java:214
main
    ActivityThread.java:7356
invoke
    Method.java
run
    RuntimeInit.java:492
main
    ZygoteInit.java:930
```

**Comment by Hirbod** [comment]
Looks like this one is the reason:
https://github.com/CrowdLinker/react-native-pager/blob/cffff21d48abebd1efbccd39348fa1b386f7ab1e/src/pager.tsx#L471

**Comment by ajsmth** [comment]
thanks for pointing this out -- these props aren't necessary anyways, although I'm curious which version of React Native throws this error

**Comment by Hirbod** [comment]
0.59.8 (Expo SDK 35)

**Comment by ajsmth** [comment]
ah, i suspect they added these in a newer version. i'll remove these props in the next release at some point tomorrow most likely

**Comment by Hirbod** [comment]
Looks more like a bug:
https://facebook.github.io/react-native/docs/0.59/accessibility

It was already there in on 0.30. But since you're going to remove it, thats perfect :)

**Comment by Hirbod** [comment]
Could you please publish a bugfix-release? Going live in 3 days, would like to avoid maintaining a fork

**Comment by ajsmth** [comment]
willl do - was it just the accessibilityRole that was causing the crash?

**Comment by Hirbod** [comment]
Yes

**Comment by ajsmth** [comment]
pushed in v0.2.1 - please verify and close the ticket! thanks

**Comment by Hirbod** [comment]
Thank you, the issue is resolved!
