### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by nadeemmar** [CrowdLinker/react-native-pager#19]
Hi, thank you for this wonderful package. I was wondering how can I flip the pages for RTL applications where cards appear to the left instead of the right. 

I have used the sample inline-cards as a basis in my implementation and it works fine for LTR but I am not sure where to start to flip the direction. I have tried changing the flexDirection on the Pager container style but that didn't work.

I appreciate your help.

**Comment by nadeemmar** [comment]
I am thinking about it and I think I could achieve what I want by reversing the order of the slides I add and handle the logic using initialIndex, minIndex and maxIndex props. 

If there is a more straightforward approach, I am all ears :)

**Comment by ajsmth** [comment]
yes, this would be my approach as well i would think. i think this could also be achievable by reversing the translations via interpolation. i'll be interested to see how you do it - if you get something working i'll add it to the docs

**Comment by nadeemmar** [comment]
Thank you for your prompt response. I have it working now by reversing the slide orders (a simple Array.reverse()) and since I control when the user can activate the next slide. I have done the following:

I define the boundaries and initial indexes in state which I set on PageProvider and Pager components:

```
 const initialIndex = I18nManager.isRTL ? survey.questions.length - 1 : 0;
 const [activeIndex, onChange] = useState(initialIndex);
 const [maxIndex, setMaxIndex] = useState(initialIndex);
 const [minIndex, setMinIndex] = useState(initialIndex);

```
On each slide, I have an action button that gets enabled when the slide form is valid. On press, I call this method:

```
updateIndexes = currentIndex => {
    if (I18nManager.isRTL) {
      if (currentIndex === minIndex) {
        setMinIndex(minIndex - 1);
      }

      onChange(activeIndex - 1);
    } else {
      if (currentIndex === maxIndex) {
        setMaxIndex(maxIndex + 1);
      }

      onChange(activeIndex + 1);
    }
  };

```

Since for me, the last slide is always going to submit the form, I simply don't call the above method.

I hope this helps anyone planning to reverse the order of slides for RTL.

**Comment by ajsmth** [comment]
awesome - thanks! i think it would be preferential to incorporate this kind of ordering in the library itself. it would certainly make the mental math simpler to use, but i'm not too familiar with I18nManager

**Comment by nadeemmar** [comment]
Yeah indeed. My experience with I18nManager is minimal. React Native mostly handles the flipping of components by itself but in cases, you need to have manual control, you just check the isRTL flag.

One more thing, for RTL, the interpolation config needs to be reversed too.

**Comment by ajsmth** [comment]
the input ranges for any interpolation config must be in order, so you'd likely have to flip the outputRanges, although it depends on your use case. in my experience the interpolations are independent of order since they describe the transformations based on the current focus of the pager

**Comment by Stringsaeed** [comment]
I also used reverse method for reversering the order of slides
```javascript 
I18nManager.isRTL ? images.slice(0).reverse().map(renderPagers) : images.map(renderPagers)
```
and for pagination component, I used `flexDirection: 'row-reverse'` in style prop to achieve fully RTL support
it's matter to me to make a **pull request** for this feature.
