### ISSUE TITLE
Problem with zIndex

### ISSUE THREAD

**Issue by tobiaslins** [CrowdLinker/react-native-pager#2]
Hey!

First of all thank you for this amazing library!
It's really performant and easy to use.

I just have one problem:
The z-index handling seems to be wrong for me
I just have following code:
```js
  <Pager
       clamp={{ next: 0 }}
       pageInterpolation={swipeCards}
       style={{ height: 180 }}>
              <View style={{ backgroundColor: "red", height: 50 }}>
                <Text>1</Text>
              </View>
              <View style={{ backgroundColor: "blue", height: 50 }}>
                <Text>2</Text>
              </View>
 </Pager>
```

Card with "1" is behind "2" but it should be the other way around. 
When I start swiping the 1 behind 2 gets swiped away.

![image](https://user-images.githubusercontent.com/2978876/64911036-2c5fa580-d71d-11e9-9c03-ac74311aa19c.png)

I tried to understand the code but was not able to fix it by myself. Do I need to handle zIndex somehow by myself?

Thanks again!

**Comment by ajsmth** [comment]
thanks for checking it out. zIndex has been the trickiest config for me to wrap my head around as it’s tough to get the right defaults. that being said you can pass it to the interpolation config, is the swipe cards the default one in the readme? i’ll try and come up with something better for zindex in the near future

**Comment by tobiaslins** [comment]
@ajsmth yes I'm using the config from the readme!
How do I embed the zIndex in there?

```js
const swipeCards = {
  transform: [
    {
      scale: {
        inputRange: [-1, 0, 1],
        outputRange: [0.95, 1, 0.95],
        clamp: Extrapolate.EXTEND,

      },
    },
    {
      translateX: {
        inputRange: [-1, 0, 1],
        outputRange: [-150, 0, 0],
      },
    },
    {
      translateY: {
        inputRange: [-1, 0, 1],
        outputRange: [0, 0, 10],
        clamp: Extrapolate.EXTEND,
      },
    },

    {
      rotate: {
        unit: "deg",
        inputRange: [-1, 0, 1],
        outputRange: [-20, 0, 0],
        clamp: Extrapolate.EXTEND,
      },
    },
  ],
};
```

**Comment by tobiaslins** [comment]
@ajsmth I think I just found out what the problem is! :)
I tried to debug your library by just adding some logs to the local node module and recognized that the function `mapConfigToStyle` looks like this `function mapConfigToStyle(offset, pageInterpolation) {`

That means that there is an older/other version on NPM?

There is no `index` parameter and thats why it's not working!

Could you please check if I'm right? Thx

**Comment by ajsmth** [comment]
hey there, yes i suspect its partly some changes I've made that haven't been pushed to npm yet. sorry about that. i'm tinkering around with this now but it seems like theres some zIndex issues here that will take some time to figure out

i've pushed v0.1.3 which will hopefully be a fix for you. zIndex configs don't work as expected so i think the default configs there should work without any changes other than upgrading to 0.1.3

**Comment by tobiaslins** [comment]
Great its working now! Thanks :)

**Comment by ajsmth** [comment]
awesome, glad to hear. I've fixed the zIndex interpolation configs now, so those will be configurable in the next release via the pageInterpolation prop just like any other style value 👍
