### ISSUE TITLE
Swipe not working with React Native CLI Project

### ISSUE THREAD

**Issue by rohitkum28** [CrowdLinker/react-native-pager#22]
Hi,

**Expected Behavior**

I am trying to create a sample application like https://snack.expo.io/H1p6iMCTB using your library. 

**Actual Behavior**

The same project when I try it with react native CLI, then the Swipe is not working. It is just Stuck on the first Slide.
To rule out any issue with my current project, I have created a fresh react native project and have only used 3 dependencies mentioned in your documentation:

     yarn add react-native-gesture-handler
     yarn add react-native-reanimated
     yarn add @crowdlinker/react-native-pager

But, I am still facing the issue. 

**Reproducible Demo**

I have put my Sample project at https://github.com/rohitkum28/react-native-pager-test.

**NOTE:** Also, https://github.com/CrowdLinker/react-native-pager/tree/master/example works on the same device so I don't think it is device issue.

**Environment**

React: 16.9.0
React native: 0.61.5
@crowdlinker/react-native-pager: ^0.2.1
react-native-gesture-handler: ^1.5.2
react-native-reanimated: ^1.4.0

Target Platform:
Android (6.0)

**Comment by ajsmth** [comment]
hey there - i suspect you have not setup the gesture handler for android on the native side, instructions for this can be found here: https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html

**Comment by rohitkum28** [comment]
Hi,

I already have installed the `react-native-gesture-handler` and since I am using react-native version 0.61.5, I should not require manual linking.
I have tried with manual linking also and it still doesn't work.
Lastly, Are you talking about [the setup with react-native-navigation](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#with-wix-react-native-navigation-https-githubcom-wix-react-native-navigation)? Because I don't see any relevance of that with it. Also, I don't see that done in the example project.

**Comment by ajsmth** [comment]
hey there - i'm referring to the additional setup required for RNGH on android e.g in main activity: 
```
package com.swmansion.gesturehandler.react.example;

import com.facebook.react.ReactActivity;
+ import com.facebook.react.ReactActivityDelegate;
+ import com.facebook.react.ReactRootView;
+ import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

public class MainActivity extends ReactActivity {

  @Override
  protected String getMainComponentName() {
    return "Example";
  }

+  @Override
+  protected ReactActivityDelegate createReactActivityDelegate() {
+    return new ReactActivityDelegate(this, getMainComponentName()) {
+      @Override
+      protected ReactRootView createRootView() {
+       return new RNGestureHandlerEnabledRootView(MainActivity.this);
+      }
+    };
+  }
}
```

**Comment by rohitkum28** [comment]
Hey, with the above changes it is working now. Thanks a lot for all your help! And Kudos for such a wonderful library.
