### ISSUE TITLE
More example code?

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [CrowdLinker/react-native-pager#3]
Hello, thanks for the awesome library. I can see multiple example images on README, can you put the code into `example` folder too?

**Comment by ajsmth** [comment]
absolutely, it's been a bit of a mess recently, i'll clean it up and provide clearer examples soon

**Comment by ajsmth** [comment]
hey there, i've cleaned up the example folder quite a bit, i think it should cover all of the examples in the README. cheers

**Comment by ajsmth** [comment]
closing this for now! let me know if theres any more examples you'd like to see.
