### ISSUE TITLE
Request to Add Product in Start Flutter

### ISSUE THREAD

**Issue by maheshwari-1153** [CrowdLinker/react-native-pager#4]
Hello,

I am Maheshwari from team [GeekyAnts](https://geekyants.com/). 

On behalf of [Start React](https://startreact.com/), we add open source products which we find helpful to the community & also we provide credits to author itself.

Let me know if you are interested showcase your product in our open source website.

If yes, then I request you to add MIT Licence in your repo.

Looking forward to hear from you.

**Comment by ajsmth** [comment]
hey there -- sure that sounds great. i've added a license to the repo, let me know if there's anything else you need me to do. cheers!

**Comment by ajsmth** [comment]
i see you've added it, i'm going to close this issue!
