### ISSUE TITLE
Android scrollable area isn't calculated correctly

### ISSUE THREAD

**Issue by gringocl** [CrowdLinker/react-native-pager#9]
First thanks for putting this pager out there!  

It seems that recent changes to `reanimated` have changed how the scrollable are is being calculated on `android`.  Our use case is using this library to horizontally page through smaller visible cards.   On android the scrollable / swipeable are is only as large as the `Page` width, active indexed element, ie the green date below.

![Screenshot 2019-10-03 16 53 34](https://user-images.githubusercontent.com/3166322/66218029-3706be00-e67d-11e9-93e0-368f2cac0d2a.png)

We have solved this by adding page width and height to the `Page` element.  I can push up a PR with these changes, if this is how this should be solved.  I am unaware of another solution.

**Comment by ajsmth** [comment]
hey there -- thanks for this. i'm wondering if you have a small reproducible example i could test out. thanks!

**Comment by gringocl** [comment]
I do not have an example currently but I will put one together.

**Comment by ajsmth** [comment]
okay great, thank you! just want to make sure we're on the same page with this

**Comment by gringocl** [comment]
Related in our current implementation. Is this issue on [`reanimated`](https://github.com/kmagiera/react-native-reanimated/issues/414).  I saw a recent commit that does some dimensional setting.

**Comment by gringocl** [comment]
https://snack.expo.io/@gringocl/android-pager

**Comment by ajsmth** [comment]
thanks for this -- i've come up with a solution that I think will work. will post updates on this soon, just want to test it out a little bit first

**Comment by ajsmth** [comment]
also i was curious about this use case in general - i would think that these indicators would be served better as pagination components responding to a pager component with your views for each date - no?

**Comment by gringocl** [comment]
I think you are correct! I’ll have to think about that for a bit!

**Comment by ajsmth** [comment]
okay cool, regardless i think this issue is important to resolve with the upcoming fix so thanks!

**Comment by ajsmth** [comment]
@gringocl i've pushed a new release (0.1.15) with the fixes, the panhandler dimensions will expand to the width of the container which should capture the pan gestures without any additional config. let me know if this helps - cheers!

**Comment by ajsmth** [comment]
after some testing, i realize some of the changes have broken flex a little bit, i'm adding an addition `containerStyle` configuration that should give us the flexibility to define the pan handler area with some sensible defaults. again, your config should work out of the box but the prop will be there if you need any extra configurations

**Comment by gringocl** [comment]
@ajsmth This solution worked great!  Thanks for getting this out so quick!  I'm going to close this as its resolved!
